permissions:
  contents: write
name: Deploy
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, [ macOS, X64], [ macOS, ARM64 ] ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        # with:
          # python-version: '3.11'
      - uses: s-weigand/setup-conda@v1
        # if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Build
        run: |
          if [ -z "${CONDA_EXE}" ]; then export CONDA_EXE=$(readlink -f $(which conda)) ; fi
          echo github.ref ${{ github.ref }}
          conda config --set solver libmamba
          . $(dirname $CONDA_EXE)/../etc/profile.d/conda.sh
          conda env remove -y -n iMolpro-github
          conda create -y -n iMolpro-github
          conda activate iMolpro-github
          # export -f conda __conda_activate __conda_reactivate __conda_hashr __add_sys_prefix_to_path
          # export PATH=$(dirname $CONDA_EXE):$PATH
          # echo $PATH
          # which conda
          bash build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*bz2
            dist/*dmg
  deploy-windows:
    name:  Deploy on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: windows_requirements.yaml
          activate-environment: iMolpro
          auto-activate-base: false
      - name: Build
        shell: pwsh
        run: .\build.ps1
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            iMolpro*.exe

      - name: Delete old latest releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 1
          delete_tag_pattern: 'latest*'
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
